CREATE TABLE `notifications` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`user_id` INT NOT NULL,
	`title` VARCHAR(80) NULL DEFAULT NULL,
	`text` VARCHAR(300) NULL DEFAULT NULL,
	`correlated_user_id` INT NULL DEFAULT '0',
	`correlated_link` VARCHAR(300) NULL DEFAULT NULL,
	`subject` VARCHAR(20) NOT NULL,
	`was_seen` TINYINT NOT NULL DEFAULT '0',
	`has_question` TINYINT NOT NULL DEFAULT '0',
	`answer` TINYINT NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=latin1;